pub mod config;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Standard EVM Gas Categories for logical grouping of execution costs.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "PascalCase")]
pub enum GasCategory {
    /// Opcodes like SSTORE
    StorageWrite,
    /// Opcodes like SLOAD
    StorageRead,
    /// Memory operations (MLOAD, MSTORE, etc.)
    Memory,
    /// Cryptographic operations (KECCAK256)
    Crypto,
    /// External calls (CALL, DELEGATECALL, etc.)
    Call,
    /// Logic and arithmetic
    Execution,
    /// Precompiled contract calls
    Precompile,
    /// Root execution frame
    Root,
    #[default]
    Other,
}

/// A single step in the EVM execution trace (equivalent to structLog).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TraceStep {
    pub pc: u64,
    pub op: String,
    pub gas: u64,
    pub gas_cost: u64,
    pub depth: u16,
    pub stack: Option<Vec<String>>,
    pub memory: Option<Vec<String>>,
    #[serde(default)]
    pub error: Option<String>,
    #[serde(default)]
    pub reverted: bool,
}

/// A single collapsed stack entry for aggregation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CollapsedStack {
    pub stack: String,
    pub weight: u64,
    pub last_pc: Option<u64>,
    #[serde(default)]
    pub target_address: Option<String>,
    #[serde(default)]
    pub resolved_label: Option<String>,
    #[serde(default)]
    pub reverted: bool,
}

/// A collapsed execution path with aggregated gas costs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HotPath {
    pub stack: String,
    pub gas: u64,
    pub percentage: f64,
    pub category: GasCategory,
}

/// The final report generated by Atupa.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Profile {
    pub version: String,
    pub transaction_hash: String,
    pub total_gas: u64,
    pub categories: HashMap<GasCategory, u64>,
    pub hot_paths: Vec<HotPath>,
    pub generated_at: String,
}

impl Profile {
    pub fn new(tx_hash: String) -> Self {
        Self {
            version: env!("CARGO_PKG_VERSION").to_string(),
            transaction_hash: tx_hash,
            total_gas: 0,
            categories: HashMap::new(),
            hot_paths: Vec::new(),
            generated_at: chrono::Utc::now().to_rfc3339(),
        }
    }
}
